const publicImages = {
    COMPANY_LOGO: `/CompanyLogo.png`,
    HomePageBackgroundImages: {
        image1: `/HomePageBackgroundImage1.png`,
        image2: `/HomePageBackgroundImage2.png`,
        image3: `/HomePageBackgroundImage3.png`,
    },
    CorporatesPageImages: {
        MAIN_LOGO: `/CorporatesPageMainLogo.png`,
        BANNER: `/CorporatesPageBanner.png`,
    },
    AboutUsPageImages: {
        MAIN_LOGO: `/AboutUsPageMainLogo.png`,
        MEET_THE_FOUNDER_SECTION: {
            IMAGE1: `/MeetTheFounderImage1.png`,
            IMAGE2: `/MeetTheFounderImage2.png`,
            IMAGE3: `/MeetTheFounderImage3.png`,
            IMAGE4: `/MeetTheFounderImage4.png`,
            ARROW1: `/Arrow1.svg`,
            ARROW2: `/Arrow2.svg`,
            ARROW3: `/Arrow3.svg`,
        },
        MEET_THE_LEADERSHIP_TEAM_SECTION: {
            MANISH_PANDEY: `/ManishPandey.png`,
            VIPUL_GUPTA: `/VipulGupta.png`,
        }
    },
    NGOsPageImages: {
        MAIN_LOGO: `/NGOsPageMainLogo.png`,
        BANNER: `/NGOsPageBanner.png`,
    },
    WHATSAPP_LOGO: `/WhatsappLogo.jpg`,
    STICKER: `Sticker.svg`,
    ILLUSTRATOR_CONTACT_US: `/Illustartion-contact-us.png`,
    NGOS_NEAR_YOU_LOGO: `/NGOsNearYouLogo.png`,
    NGOLogos: {
        SACHDEVA_FOUNDATION: `/SachdevaFoundationLogo.svg`,
        ANGELS_FOR_ANIMALS: `/AngelsForAnimals.svg`,
        EL_SHADDAI: `/ElShaddai.svg`,
        AGAPE_AIDS_ORPHAN_CARE: `/AgapeAidsOrphanCare.svg`,
        PEHCHAAN_THE_STREET_SCHOOL: `/PehchaanTheStreetSchool.svg`,
        EARTH_FOCUS: `/EarthFocus.svg`,
        AYANG: `/Ayang.svg`,
    },
    CORPORATE_LOGOS: {
        CREATE_AN_INFLUENCE: '/CorporatePartner1.svg',
        CONFEDERATION_OF_INDIAN_INDUSTRY: `/confederation-of-indian-industry-cii-logo.png`,
        LOGO2: '/CorporatePartner2.svg',
        LOGO3: '/CorporatePartner3.svg',
        LOGO4: '/CorporatePartner4.svg',
        LOGO5: '/CorporatePartner5.svg',
        LOGO6: '/CorporatePartner6.svg',
        LOGO7: '/CorporatePartner7.svg',
        LOGO8: '/CorporatePartner8.svg',
        CENTILLION: `/centillionlogo (1).png`,
    },
    CAUSE_LOGOS: {
        ANIMALS: '/Animals.svg',
        CHILDREN: `/Education.svg`,
        ELDERLY: '/Elderly.svg',
        HUNGER: '/Hunger.svg',
        WOMEN: '/Women.svg',
        LGBTQ: '/LGBTQ.svg',
        FAITH: '/Faith.svg',
        DISASTER_RELIEF: '/Disaster Relief.svg',
        ENVIRONMENT_AND_CLIMATE_CHANGE: '/Environment and Climate Change.svg',
        DISABILITY: '/Disability.svg',
    },
    WORK_AROUNDS: {
        OUR_IMPACT: `/Our-Impact-section.png`,
        WHAT_WE_CARE_ABOUT: `/What-we-care-about-section.png`,
        NGOS_NEAR_YOU: `/Find-NGO's-near-you-section.png`,
        CORPORATES_PARTNERS: `/Corporate-Partners-section.png`,
        EVENT_DETAILS_BANNER: `/EventDetailsBanner.png`,
        EVENT_PERKS: `/EventPerks.png`,
        EVENTS_PAGE_BANNER: `/EventsPageBanner.jpg`,
        EVENT_CARD_THUMBNAIL: `/EventThumbnail.png`,
        FOUNDER_SECTION: `/Founder-Journey-section (1).png`,
        FOUNDER_SECTION_MOBILE_VIEW: `/Section-journey.png`,
        FRIEND_OF_TKC: `/FriendOfTKC.png`,
    },
    FILTER_ICON: `/FilterIcon.svg`,
    CITIES: {
        DELHI: `/Delhi.jpg`,
        MUMBAI: `/Mumbai.jpg`,
        CHENNAI: `/Chennai.jpg`,
        BENGALURU: `/Bengaluru.jpg`,
        JAIPUR: `/Jaipur.jpg`,
        KOLKATA: `/Kolkata.jpg`
    },
};

export default publicImages;